spring.application.name=backend

# Puerto del servidor
server.port=8080

# Conexión a SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=clinica_cunina;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuración JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT (lo usaremos después)
jwt.secret=claveSuperSecretaParaFirmarTokensCunina2026
jwt.expiration=86400000

# Logging
logging.level.org.hibernate.SQL=DEBUG